#This file stores configuration options for Iris, such as the currently active shaderpack
#Los shaders no vienen en el pack: quien quiera los pone desde el menu de Iris.
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
